Pré processar o arquivo

In [ ]:
import sys

InputFile = "lots_text.txt"
f = open(InputFile, "r", encoding='utf-8')

txt = f.read()
for t in (("alegria", "positivo"), ("raiva", "negativo"), ("medo", "negativo"), ("desgosto", "negativo"), ("tristeza", "negativo")):
    txt = txt.replace(*t)

with open(InputFile, 'w', encoding='utf-8') as f:
    f.write(txt)                  

f.close()    

In [ ]:
with open(InputFile,"r+", encoding='utf-8') as f:
    new_f = f.readlines()
    f.seek(0)
    for line in new_f:
        if "surpresa" not in line:
            f.write(line)
    f.truncate()

In [ ]:
from sklearn import svm
from sklearn.model_selection import cross_val_score, cross_val_predict
from sklearn.metrics import confusion_matrix
from sklearn.utils.multiclass import unique_labels
from sklearn.metrics import classification_report
from operator import itemgetter, attrgetter
import numpy as np
import nltk
import math
nltk.download(['stopwords','rslp','punkt'])


[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package rslp to /root/nltk_data...
[nltk_data]   Package rslp is already up-to-date!
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


True

In [ ]:
stopwords = nltk.corpus.stopwords.words('portuguese') 
stopwords+= (',','.','(',')','"',"'",'´','`','!','$','%','&','...','-',':',';','?','``','\'\'') 
stopwords+= ('a','e','i','o','u','A','E','I','O','U') 

stemmer = nltk.stem.RSLPStemmer()




In [ ]:
InputFile = "lots_text.txt"

f = open(InputFile, "r", encoding="utf-8")
data = []


while True:
    for line in f:
        text = line.split(';')
                
        tokens = nltk.word_tokenize(text[1]) 
        tokensLimpo = []
        for palavra in tokens:
            if (palavra not in stopwords):
                tokensLimpo.append(stemmer.stem(palavra)) 
        instance = (text[0],tokensLimpo)  
        data.append(instance)
    if line == 'positivo;felipe':
        break

    

In [ ]:
allwords = []
for text in data:
    for word in text[1]:
        if word not in allwords:
            allwords.append(word)  
            allwords.sort()
qtdPalavras = len(allwords)

In [ ]:
features = []
labels = []

for texto in data:
    ocorrencias = []
    labels.append(texto[0])
    
    for palavra in allwords:
        if palavra in texto[1]:
            ocorrencias.append(texto[1].count(palavra))
        else:
            ocorrencias.append(0)
    features.append(ocorrencias)

   

In [ ]:
print('----------------------------------------------') 
print("Instâncias 3 classes: "+str(len(labels)))
print("Features 3 classes: "+str(len(features[0])))

----------------------------------------------
Instâncias 3 classes: 1747
Features 3 classes: 6497


In [ ]:
def SVM(features, labels, folds):
    print('Linear SVM start: ')
    clf = svm.SVC(kernel='linear', C=1)
    predict = cross_val_predict(clf, features, labels, cv=folds)
    cm = confusion_matrix(labels, predict)
    print(cm)
    print(classification_report(labels, predict, target_names=np.unique(labels)))
    print('----------------------------------------------')
    return predict, cm

In [ ]:
predict = SVM(features, labels, 10)

Linear SVM start: 
[[885 113  23]
 [165 340  36]
 [ 72  70  43]]
              precision    recall  f1-score   support

    negativo       0.79      0.87      0.83      1021
      neutro       0.65      0.63      0.64       541
    positivo       0.42      0.23      0.30       185

    accuracy                           0.73      1747
   macro avg       0.62      0.58      0.59      1747
weighted avg       0.71      0.73      0.71      1747

----------------------------------------------
